name = "cse110-sp26-group15"
compatibility_date = "2026-05-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sitrep-db"
database_id = "6a6922f4-290d-4f1e-a0a5-cd7e9934b2e6"
migrations_dir = "./db/migrations"